
github: [OmarrSakr]  # اسم المستخدم الخاص بك في GitHub لتفعيل زر Sponsor
# patreon: OmarSakr  # اسم المستخدم الخاص بك في Patreon 
buy_me_a_coffee: omarrhussev  # اسم المستخدم الخاص بك في Buy Me a Coffee
# custom: ["https://www.patreon.com/OmarSakr", "https://www.buymeacoffee.com/omarrhussev"]  # روابط مخصصة لدعمك
