
github: [OmarrSakr]  # اسم المستخدم الخاص بك في GitHub لتفعيل زر Sponsor
buy_me_a_coffee: omarrhussev  # اسم المستخدم الخاص بك في Buy Me a Coffee
patreon: OmarSakr  # اسم المستخدم الخاص بك في Patreon
# custom: ["https://www.patreon.com/OmarSakr", "https://www.buymeacoffee.com/omarrhussev"]  # روابط مخصصة لدعمك
